create table if not exists post (
    id bigint generated by default as identity primary key,
    note_id varchar(128) unique,
    status varchar(32) not null default 'published',
    source_path varchar(500),
    content_hash varchar(128),
    title varchar(200) not null,
    slug varchar(120) not null unique,
    markdown_content clob not null,
    summary varchar(500),
    create_time timestamp not null,
    update_time timestamp not null,
    last_sync_time timestamp
);

create index if not exists idx_post_update_time on post (update_time desc, id desc);
create index if not exists idx_post_status on post (status);

create table if not exists tag (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    slug varchar(120) not null unique,
    create_time timestamp not null,
    update_time timestamp not null
);

create table if not exists category (
    id bigint generated by default as identity primary key,
    name varchar(120) not null unique,
    slug varchar(120) not null unique,
    create_time timestamp not null,
    update_time timestamp not null
);

create table if not exists post_tag (
    post_id bigint not null,
    tag_id bigint not null,
    primary key (post_id, tag_id),
    constraint fk_post_tag_post foreign key (post_id) references post (id),
    constraint fk_post_tag_tag foreign key (tag_id) references tag (id)
);

create index if not exists idx_post_tag_tag_id on post_tag (tag_id);

create table if not exists post_category (
    post_id bigint not null,
    category_id bigint not null,
    primary key (post_id, category_id),
    constraint fk_post_category_post foreign key (post_id) references post (id),
    constraint fk_post_category_category foreign key (category_id) references category (id)
);

create index if not exists idx_post_category_category_id on post_category (category_id);
