apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # Global (shared)
  - global-configmap.yaml

  # Per-service configs
  - gateway/configmap.yaml
  - blog/configmap.yaml

  # MySQL
  - mysql/pv-pvc.yaml
  - mysql/configmap.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml

  # Gateway
  - gateway/deployment.yaml
  - gateway/service.yaml

  # Blog
  - blog/deployment.yaml
  - blog/service.yaml

  # Web
  - web/deployment.yaml
  - web/service.yaml

