apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  # Global (shared)
  - global-configmap.yaml

  # Per-service configs
  - gateway/configmap.yaml
  - blog/configmap.yaml

