imagePullSecrets:
  - name: acr-secret

deploymentMode: SingleBinary

loki:
  auth_enabled: false
  image:
    registry: crpi-ekwujpeg6f954ar3.cn-wulanchabu.personal.cr.aliyuncs.com
    repository: cloud-ops-hub/loki
    tag: 3.7.0-amd64
    pullPolicy: IfNotPresent
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    retention_period: 168h
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    volume_enabled: true

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 768Mi

gateway:
  enabled: true
  image:
    registry: crpi-ekwujpeg6f954ar3.cn-wulanchabu.personal.cr.aliyuncs.com
    repository: cloud-ops-hub/nginx-unprivileged
    tag: 1.29-alpine-amd64
    pullPolicy: IfNotPresent

minio:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: false

test:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0
