apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-assets-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/cloud-ops/blog-assets
    type: DirectoryOrCreate
  claimRef:
    namespace: cloud-ops
    name: blog-assets-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-assets-pvc
  namespace: cloud-ops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: blog-assets-pv
