apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: cloud-ops
  labels:
    app: blog-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: blog-service
